### ISSUE TITLE
Cannot compile on Windows MINGW

### ISSUE THREAD

**Issue by GrantKlassy** [kwizatz88/GsyncSwitch#1]
Hello,

This gsync switch looks great. I have an issue that is only fixed by turning Gsync on and back off. I am hoping your application will allow me to do that quickly. 

However, I cannot compile this repo on MINGW. I cloned the repo and downloaded NVAPI from here [1]. I copied the NVAPI files into the GsyncSwitchEXE directory and ran  `gcc ./GsyncSwitchEXE.cpp`.  Here is the compiler output

```
Grant@BLD MINGW64 /c/Users/Grant/Desktop/git/GsyncSwitch/GsyncSwitchEXE/GsyncSwitchEXE
$ gcc ./GsyncSwitchEXE.cpp
In file included from ./nvapi_lite_d3dext.h:35,
                 from ./nvapi.h:6,
                 from ./GsyncSwitchEXE.cpp:4:
./nvapi_lite_salstart.h:821:32: warning: '__success' initialized and declared 'extern'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:32: note: in definition of macro 'NVAPI_INTERFACE'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:42: error: expected primary-expression before 'return'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                          ^~~~~~
./nvapi_lite_salstart.h:821:42: note: in definition of macro 'NVAPI_INTERFACE'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                          ^~~~~~
./nvapi_lite_salstart.h:821:32: warning: '__success' initialized and declared 'extern'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:32: note: in definition of macro 'NVAPI_INTERFACE'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:32: error: redefinition of 'int __success'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:32: note: in definition of macro 'NVAPI_INTERFACE'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:32: note: 'int __success' previously defined here
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:32: note: in definition of macro 'NVAPI_INTERFACE'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                ^~~~~~~~~
./nvapi_lite_salstart.h:821:42: error: expected primary-expression before 'return'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl
      |                                          ^~~~~~
./nvapi_lite_salstart.h:821:42: note: in definition of macro 'NVAPI_INTERFACE'
  821 | #define NVAPI_INTERFACE extern __success(return == NVAPI_OK) NvAPI_Status __cdecl

```

[1] https://developer.nvidia.com/gameworksdownload

**Comment by GrantKlassy** [comment]
@kwizatz88 If you have recommended compilation steps for Windows I'd be happy to follow them, I may be doing something wrong

**Comment by kwizatz88** [comment]
looks like someone had your exact issue here :
https://geeksqa.com/include-of-nvidia-s-nvapi-h-causes-compilation-errors

seems to be a compiler issue

**Comment by GrantKlassy** [comment]
Ah good find, my Googling was not thorough enough. Although I am getting less errors, I am still getting compile errors after making the suggested fix that you linked (moving down `#include"nvapi_lite_salstart.h"`).

I am just going to try downloading Visual Studio and opening your solution next.

![image](https://user-images.githubusercontent.com/28637437/190525106-fb0413eb-2aca-4658-8416-e67c210e038b.png)

**Comment by GrantKlassy** [comment]
It looks like just using Visual Studio instead of VSCode / MINGW solved my problems.

Steps to fix
1. Download Visual Studio https://visualstudio.microsoft.com/downloads/
2. Download .NET 4.8 Developer pack and install https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?cid=msbuild-developerpacks
3. Clone repo
4. Download NVAPI https://developer.nvidia.com/gameworksdownload
5. Extract NVAPI (R515-developer) and copy files inside folder to base of repo
6. Open the solution file in Visual Studio and build. The EXE is now in ./bin/debug and runs properly for me!
