### ISSUE TITLE
Few Bugs

### ISSUE THREAD

**Issue by jh30uk** [kwizatz88/GsyncSwitch#6]
Updated today and my Custom Config is reset, used the option in menu to revert this but does nothing.

PIA to change it all each time and the Monitor name it gives is not the one in NVP (like it claims) and I name it my LG model anyway,

Also seems as Monitors 1 and Monitor 2 are round the wrong way as I only have one and removing Monitor 2 removed primary monitor/name.

**Comment by kwizatz88** [comment]
unfortunately updating override the config.ini file, I can't do anything for that
but that's why I added the new menu "try to open previous configuration" : what happens when you click on that ?
you can also use the "Open GsyncSwitch location folder" and go one folder higher to find the previous install with your older config.ini

**Comment by kwizatz88** [comment]
For people only using 1 monitor like you, I'll add an option in config.ini to remove the 4 useless menus

**Comment by jh30uk** [comment]
Thanks, as I said nothing happens using the revert option it simply opens the current new Config with all new/wrong info.

**Comment by kwizatz88** [comment]
I updated the app for the 1 monitor option in config.ini

"Any way to stop the pop up at startup opening in a different location on the screen each time (Win 7/10/11 issue) or a silent option unless an update is needed?"
I don't understand this one, can you explain ?

**Comment by kwizatz88** [comment]
"Try to open previous configuration" menu doesn't revert anything, it just opens your previous config.ini file, so you can copy what you want here to manually put it in new configuration

**Comment by jh30uk** [comment]
It opened the brand new one not the old one I had edited.

**Comment by jh30uk** [comment]
I readded my edited setting manually typing and hid the Xbox setting as do not need/use and now it does not start.

**Comment by kwizatz88** [comment]
do you still have any issue or is it fixed now ?

**Comment by jh30uk** [comment]
Old Config 

[blank]

[monitors]
monitor1Label=LG 32GN600
monitor1Id=LG 32GN600

[frequencies]
To 165 Hz=2560 1440 32 165
To 144 Hz=2560 1440 32 144
To 120 Hz=2560 1440 32 120

[frameLimiterMaxFps]
maxFps=165


New Config (will not load).

[blank]

[monitors]
use2monitors=false
#don't bother setting this if you set use2monitors=false :
monitor1Label=QN95A
monitor1Id=Q95A
monitor2Label=QN95B
monitor2Id=QBQ95

[frequencies]
To 144 Hz=2560 1440 32 165
To 144 Hz=2560 1440 32 144
To 120 Hz=2560 1440 32 120

[frameLimiterMaxFps]
maxFps=165
[others]
showControllerStatus=false

**Comment by kwizatz88** [comment]
If you copied your old config.ini, settings might be missing in it
here is the original one :
[blank]

[monitors]
use2monitors=true
#don't bother setting this if you set use2monitors=false :
monitor1Label=QN95A
monitor1Id=Q95A
monitor2Label=QN95B
monitor2Id=QBQ95

[frequencies]
To 144 Hz=3840 2160 32 144
To 120 Hz=3840 2160 32 120

[frameLimiterMaxFps]
maxFps=144

[others]
showControllerStatus=true

**Comment by jh30uk** [comment]
That went fine it was this 2nd new one that did not, and I did not copy Config this time as of new items,

**Comment by kwizatz88** [comment]
This should work for you :

[blank]

[monitors]
use2monitors=false
#don't bother setting this if you set use2monitors=false :
monitor1Label=QN95A
monitor1Id=Q95A
monitor2Label=QN95B
monitor2Id=QBQ95

[frequencies]
To 165 Hz=2560 1440 32 165
To 144 Hz=2560 1440 32 144
To 120 Hz=2560 1440 32 120

[frameLimiterMaxFps]
maxFps=165

[others]
showControllerStatus=false

**Comment by jh30uk** [comment]
That worked, funny it looked the same as mine.

**Comment by kwizatz88** [comment]
It's because you added the same key for 2 lines, but you can use as much lines as you want, even 20

**Comment by kwizatz88** [comment]
you had twice "To 144 Hz"

**Comment by jh30uk** [comment]
Which as 1 was 120, 2 was 144 and 3 was 165?

**Comment by kwizatz88** [comment]
this is what you wrote before :
[frequencies]
To 144 Hz=2560 1440 32 165
To 144 Hz=2560 1440 32 144
To 120 Hz=2560 1440 32 120

**Comment by kwizatz88** [comment]
If it's ok I close the issue, have a nice day

**Comment by jh30uk** [comment]
Yea I get it now as I copied /paste line then edited.

**Comment by jh30uk** [comment]
Sure thanks.

**Comment by kwizatz88** [comment]
👍
