### ISSUE TITLE
[Feature request] Toggle gsync off/on on command line

### ISSUE THREAD

**Issue by mtjohnson47** [kwizatz88/GsyncSwitch#8]
I have a bug with my main monitor that causes it to black screen when I start a game while gsync is active.  I found this program while looking for a solution to toggle gsync off and back on without opening nvidia control panel.  It works great but the design of the program is such that it can only be used from my primary monitor, which I can't do when the screen is blacked out.

So, I'm requesting that command line arguments be added which will activate the buttons on the menu.  I'll create a desktop shortcut which runs the program with those arguments.

**Comment by kwizatz88** [comment]
before V3, there used to be an EXE file making the switch :
https://github.com/kwizatz88/GsyncSwitch/releases

just take the V2 and inside the archive use the EXE one and make a shortcut to it, launching this exe will switch Gsync
